name: Build and Publish Docker Image

on:
  push:
    branches: main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Image name and version
        run: |
          echo "IMAGE_NAME=$(echo '${{ github.repository_owner }}/${{ github.event.repository.name }}' | tr '[:upper:]' '[:lower:]')" >>${GITHUB_ENV};

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5

        with:
          context: . # Path to your Dockerfile
          file: ./Dockerfile # Path to your Dockerfile. Adjust if needed.
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}



      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}